---
- name: Create network
  community.docker.docker_network:
    name: "{{ NETname }}"
    driver: overlay

- name: services
  vars:
    names: "{{ item.name }}"
    version: "{{ item.version }}"
  include_tasks: 
    file: "../services/{{ item.name }}/service.yml"
    apply:
      tags: "{{ item.name }}"
  tags: always
  loop: "{{ services }}"





    


    