---
- name:  " [{{ names }}] configuration of secret"
  block:
    - name:  " [{{ names }}] Create secret"
      include_tasks: "secret_creation.yml"

  rescue:
    - name: " [{{ names }}] Remove services"
      community.docker.docker_swarm_service:
        name: "{{ names }}"
        state: absent

    - name:  " [{{ names }}] Create secret"
      include_tasks: "secret_creation.yml"
  tags: "{{ names }}"
