---
- name: "[{{ names }}] Create secret"
  community.docker.docker_secret:
    name: "{{ names }}.env"
    data: "{{ envFile | b64encode }}"
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present
  vars:
    envFile: "{{ lookup('template', names ~ '/.env.jinja2') }}"

- name: "deb"
  vars:
    envFile: "{{ lookup('template', names ~ '/.env.jinja2') }}"
  debug:
    msg: "{{ envFile }}"